
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:47 (project)"
    message: |
      The system is: Linux - 6.17.0-35-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/gcc-14 
      Build flags: -fdefinitely-invalid
      Id flags:  
      
      The output was:
      1
      gcc-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/gcc-14 
      Build flags: -fdefinitely-invalid
      Id flags: -c 
      
      The output was:
      1
      gcc-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/gcc-14 
      Build flags: -fdefinitely-invalid
      Id flags: -Aa 
      
      The output was:
      1
      gcc-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/gcc-14 
      Build flags: -fdefinitely-invalid
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      gcc-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/gcc-14 
      Build flags: -fdefinitely-invalid
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      gcc-14: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
      gcc-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      gcc-14: error: unrecognized command-line option ‘--target=arm-arm-none-eabi’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/gcc-14 
      Build flags: -fdefinitely-invalid
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      gcc-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/gcc-14 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/3.31.10/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/g++-14 
      Build flags: -fdefinitely-invalid
      Id flags:  
      
      The output was:
      1
      g++-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/g++-14 
      Build flags: -fdefinitely-invalid
      Id flags: -c 
      
      The output was:
      1
      g++-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/g++-14 
      Build flags: -fdefinitely-invalid
      Id flags: --c++ 
      
      The output was:
      1
      g++-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      g++-14: error: unrecognized command-line option ‘--c++’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/g++-14 
      Build flags: -fdefinitely-invalid
      Id flags: --ec++ 
      
      The output was:
      1
      g++-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      g++-14: error: unrecognized command-line option ‘--ec++’; did you mean ‘-Weffc++’?
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/g++-14 
      Build flags: -fdefinitely-invalid
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      g++-14: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
      g++-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      g++-14: error: unrecognized command-line option ‘--target=arm-arm-none-eabi’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/g++-14 
      Build flags: -fdefinitely-invalid
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      g++-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/g++-14 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/3.31.10/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:47 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-AUDjUn"
      binary: "/home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-AUDjUn"
    cmakeVariables:
      CMAKE_C_FLAGS: "-fdefinitely-invalid"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-fdefinitely-invalid"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-AUDjUn'
        
        Run Build Command(s): /home/ms/.py-venv/bin/ninja -v cmTC_45ed2
        [1/2] /usr/bin/gcc-14   -fdefinitely-invalid    -v -o CMakeFiles/cmTC_45ed2.dir/CMakeCCompilerABI.c.o -c /opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        FAILED: [code=1] CMakeFiles/cmTC_45ed2.dir/CMakeCCompilerABI.c.o 
        /usr/bin/gcc-14   -fdefinitely-invalid    -v -o CMakeFiles/cmTC_45ed2.dir/CMakeCCompilerABI.c.o -c /opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        Using built-in specs.
        COLLECT_GCC=/usr/bin/gcc-14
        OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
        OFFLOAD_TARGET_DEFAULT=1
        gcc-14: error: unrecognized command-line option '-fdefinitely-invalid'
        Target: x86_64-linux-gnu
        Configured with: ../src/configure -v --with-pkgversion='Ubuntu 14.2.0-4ubuntu2~24.04.1' --with-bugurl=file:///usr/share/doc/gcc-14/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2,rust --prefix=/usr --with-gcc-major-version-only --program-suffix=-14 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-libstdcxx-backtrace --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-14-FpLBWZ/gcc-14-14.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-14-FpLBWZ/gcc-14-14.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 14.2.0 (Ubuntu 14.2.0-4ubuntu2~24.04.1) 
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/cmake-3.31.10-linux-x86_64/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:47 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/gcc-14"
    directories:
      source: "/home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-Shfb0v"
      binary: "/home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-Shfb0v"
    cmakeVariables:
      CMAKE_C_FLAGS: "-fdefinitely-invalid"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-fdefinitely-invalid"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-Shfb0v'
        
        Run Build Command(s): /home/ms/.py-venv/bin/ninja -v cmTC_fdcca
        [1/2] /usr/bin/gcc-14   -fdefinitely-invalid -o CMakeFiles/cmTC_fdcca.dir/testCCompiler.c.o -c /home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-Shfb0v/testCCompiler.c
        FAILED: [code=1] CMakeFiles/cmTC_fdcca.dir/testCCompiler.c.o 
        /usr/bin/gcc-14   -fdefinitely-invalid -o CMakeFiles/cmTC_fdcca.dir/testCCompiler.c.o -c /home/ms/ms-base/work/phd/compression-algs-eval/compression-eval/corpus/src/_shared/c/mold/.build/mold-failure-cleanup/CMakeFiles/CMakeScratch/TryCompile-Shfb0v/testCCompiler.c
        gcc-14: error: unrecognized command-line option ‘-fdefinitely-invalid’
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
